// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiloqejjrykfbgmywitn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpbG9xZWpqcnlrZmJnbXl3aXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMTU5NTIsImV4cCI6MjA1Mzc5MTk1Mn0.NxRjM11ak9qdfaD1nvJJFUjwuxXt_5yWrbC2w4gzFbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);